export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Education } from "./Education";
export { default as Footer } from "./Footer";
export { default as FunFact } from "./FunFact";
export { default as Home } from "./Home";
export { default as Project } from "./Project";
export { default as Testimonial } from "./Testimonial";
export { default as Work } from "./Work";